Fixed NaNs, various fixes and improvements - Misc.cs: ValidateNaN(): Function to return input or fallback if NaN - KeyManager.cs: Fixed `speedTrend` being stuck as NaN - Typing.cs: Fixed lost focus when moving to the next quote - Typing.cs: Fixed ctrl+backspace sometimes throwing an IndexOutOfRange - Typing.cs: Restart lesson when all text is erased - Typing.cs: Removed the old text input code - Other: Code formatting improvements

diff --git a/Builds/build b/Builds/build
--- a/Builds/build
+++ b/Builds/build
@@ -7,14 +7,14 @@
 # TODO: Only building for Linux works (presumably because of IL2CPP)
 
 cd ..
-unityInstall=\
+unityPath=\
 "$HOME/.unity/\
 $(cat './ProjectSettings/ProjectVersion.txt' | grep 'm_EditorVersion:' | sed 's/.*\: //g')\
 /Editor/Unity"
-echo $unityInstall
+echo $unityPath
 
 tail -f ~/.config/unity3d/Editor.log &
 processID=$!
-$unityInstall -logFile "$HOME/.config/unity3d/Editor.log" -quit -batchmode -projectPath "$(pwd)" -executeMethod AutoBuild.Build "$@"; kill $processID || { echo "Build failed!"; exit 2; }
+$unityPath -logFile "$HOME/.config/unity3d/Editor.log" -quit -batchmode -projectPath "$(pwd)" -executeMethod AutoBuild.Build "$@"; kill $processID || { echo "Build failed!"; exit 2; }
 
 cd -
